#!/bin/sh

python3 -m venv ~/env1
source ~/env1/bin/activate
pip install --upgrade pip
pip install --upgrade -r ./requirements
complete -C '/root/env1/bin/aws_completer' aws

# starting localstack
localstack start -d

# upgrade terraform to 0.12.21
wget https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip -P /tmp
unzip /tmp/terraform_0.12.21_linux_amd64.zip -d /tmp
mv /tmp/terraform /usr/bin/terraform
